### ISSUE TITLE
I have a fix for multiple invocations in same scope

### ISSUE THREAD

**Issue by Boscop** [nodakai/rust-static_assert_macro#4]
I have a fix for multiple invocations in the same scope:
```rust
const _: () = { fn _fn_for_static_assert(_: [i8; ($e) as usize - 1]) {} };
```

You can see it working here:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ecfb95fde735d728db8080a0d31a50a3

**Comment by Boscop** [comment]
Actually no need for the function:

https://docs.rs/static_assertions/1.1.0/src/static_assertions/const_assert.rs.html#55

> const _: [(); 0 - !{ const ASSERT: bool = $x; ASSERT } as usize] = [];

**Comment by nodakai** [comment]
That's a great insight! I'm preparing a new release

**Comment by nodakai** [comment]
@all-contributors please add @Boscop for his ingenuity on avoiding name collisions among multiple invocations in a single scope

**Comment by nodakai** [comment]
@all-contributors please add @Boscop for code
